from django.conf.urls import url

from . import views

app_name = "scheduler"
urlpatterns = [
    # ex: /scheduler/
    url(r'^$', views.index, name='index'),
    # ex: /scheduler/generate/
    url(r'^generate-schedule/$', views.generateSchedule, name='generate-schedule'),
    # ex: /scheduler/generate/edit/
    #url(r'^generate-schedule/edit/$', views.scheduleEdit, name='schedule-edit'),
    # ex: /scheduler/generate/delete/
    url(r'^generate-schedule/delete/$', views.tempScheduleDelete, name='temp-schedule-delete'),
    # ex: /scheduler/generate/save/
    url(r'^generate-schedule/save/$', views.scheduleSave, name='schedule-save'),
    # ex: /scheduler/generate/override/
    url(r'^generate-schedule/override/$', views.scheduleOverride, name='schedule-override'),
    # ex: /scheduler/employees/
    url(r'^employees/$', views.manageEmployees, name='manage-employees'),
    # ex: /scheduler/employees/5/update/
    url(r'^employees/(?P<pk>[0-9]+)/update/$', views.EmployeeUpdate.as_view(), name='employee-update'),
    # ex: /scheduler/employees/5/delete/
    url(r'^employees/(?P<pk>[0-9]+)/delete/$', views.EmployeeDelete.as_view(), name='employee-delete'),
    # ex: /scheduler/requests/
    url(r'^requests/$', views.requests, name='requests'),
    # ex: /scheduler/requests/prompt/
    url(r'^requests/prompt/$', views.requestPrompt, name='request-prompt'),
    # ex: /scheduler/requests/vacation-request/
    url(r'^requests/vacation-request/$', views.vacationRequest.as_view(), name='vacation-request'),
    # ex: /scheduler/requests/shift-request/
    url(r'^requests/shift-request/$', views.shiftRequest.as_view(), name='shift-request'),
    # ex: /scheduler/requests/recurring-shift-request/
    url(r'^requests/recurring-shift-request/$', views.recurringShiftRequest.as_view(), name='recurring-shift-request'),
    # ex: /scheduler/requests/vacation-request/5/update/
    url(r'^requests/vacation-request/(?P<pk>[0-9]+)/update/$', views.VacationRequestUpdate.as_view(), name='vacation-request-update'),
    # ex: /scheduler/requests/vacation-request/5/delete/
    url(r'^requests/vacation-request/(?P<pk>[0-9]+)/delete/$', views.VacationRequestDelete.as_view(), name='vacation-request-delete'),
    # ex: /scheduler/requests/shift-request/5/update/
    url(r'^requests/shift-request/(?P<pk>[0-9]+)/update/$', views.ShiftRequestUpdate.as_view(), name='shift-request-update'),
    # ex: /scheduler/requests/shift-request/5/delete/
    url(r'^requests/shift-request/(?P<pk>[0-9]+)/delete/$', views.ShiftRequestDelete.as_view(), name='shift-request-delete'),
    # ex: /scheduler/requests/recurring-shift-request/5/update/
    url(r'^requests/recurring-shift-request/(?P<pk>[0-9]+)/update/$', views.RecurringShiftRequestUpdate.as_view(), name='recurring-shift-request-update'),
    # ex: /scheduler/requests/recurring-shift-request/5/delete/
    url(r'^requests/recurring-shift-request/(?P<pk>[0-9]+)/delete/$', views.RecurringShiftRequestDelete.as_view(), name='recurring-shift-request-delete'),
    # ex: /scheduler/schedules/
    url(r'^schedules/$', views.schedules, name='schedules'),
    # ex: /scheduler/schedules/yyyy-mm-dd/
    url(r'^schedules/(?P<date>\d{4}-\d{2}-\d{2})/$', views.schedules, name='schedules'),
    # ex: /scheduler/coverage/yyyy-mm-dd/
    url(r'^schedules/coverage/$', views.scheduleCoverage, name='schedule-coverage'),
    url(r'^schedules/coverage/(?P<date>\d{4}-\d{2}-\d{2})/$', views.scheduleCoverage, name='schedule-coverage'),
    # ex: /scheduler/schedules/edit/yyyy-mm-dd/
    url(r'^schedules/edit/$', views.editSchedule, name='schedule-edit'),
    url(r'^schedules/edit/(?P<date>\d{4}-\d{2}-\d{2})/$', views.editSchedule, name='schedule-edit'),
    # ex: /scheduler/schedules/delete/
    url(r'^schedules/delete/$', views.deleteSchedule, name='schedule-delete'),
]