# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 02:37
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(default='', max_length=20)),
                ('position', models.CharField(choices=[('SM', 'Senior Manager'), ('AM', 'Assistant Manager'), ('SIM', 'Store Inventory Merchandiser'), ('SLIM', 'Shift Leader something Manager'), ('BSI', 'Bookseller I'), ('BSII', 'Bookseller II'), ('PT', 'Part Time Bookseller'), ('TB', 'Temporary Bookseller')], default='BSII', max_length=20)),
                ('hours', models.IntegerField(default=35, validators=[django.core.validators.MaxValueValidator(35)])),
                ('quad', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekStart', models.DateField(default=datetime.date.today)),
                ('mondayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('tuesdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('wednesdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('thursdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('fridayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('saturdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('sundayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scheduler.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.Request')),
                ('date', models.DateField(default=datetime.date.today)),
                ('shift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('recurring', models.BooleanField(default=False)),
            ],
            bases=('scheduler.request',),
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.Request')),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
            ],
            bases=('scheduler.request',),
        ),
        migrations.AddField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Employee'),
        ),
    ]
