# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekStart', models.DateField(default=datetime.date.today)),
                ('mondayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('tuesdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('wednesdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('thursdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('fridayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('saturdayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('sundayShift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scheduler.Employee')),
            ],
        ),
    ]
