# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_tempschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringScheduleRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.Request')),
                ('weekDay', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], default='M', max_length=10)),
                ('shift', models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15)),
            ],
            bases=('scheduler.request',),
        ),
        migrations.RemoveField(
            model_name='shiftrequest',
            name='recurring',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('SM', 'Senior Manager'), ('AM', 'Assistant Manager'), ('SIM', 'Store Inventory Merchandiser'), ('SLIM', 'Shift Leader'), ('BSI', 'Bookseller I'), ('BSII', 'Bookseller II'), ('PT', 'Part Time Bookseller'), ('TB', 'Temporary Bookseller')], default='BSII', max_length=20),
        ),
    ]
