# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20181205_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringScheduleRequest',
            new_name='RecurringShiftRequest',
        ),
    ]
