# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20181205_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringshiftrequest',
            name='request_ptr',
        ),
        migrations.DeleteModel(
            name='RecurringShiftRequest',
        ),
    ]
