# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_recurringshiftrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='buyer',
            field=models.BooleanField(default=False),
        ),
    ]
