# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_employee_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringshiftrequest',
            name='shift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='shift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempschedule',
            name='fridayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempschedule',
            name='mondayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempschedule',
            name='saturdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempschedule',
            name='sundayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempschedule',
            name='thursdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempschedule',
            name='tuesdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempschedule',
            name='wednesdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='fridayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='mondayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='saturdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='sundayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='thursdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='tuesdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='wednesdayShift',
            field=models.CharField(choices=[('OFF', 'Off'), ('V', 'Vacation'), ('6am', '6am-2pm'), ('7am', '7am-3pm'), ('7:30am', '7:30am-3:30pm'), ('8am', '8am-4pm'), ('9am', '9am-5pm'), ('10am', '10am-6pm'), ('11am', '11am-7pm'), ('12pm', '12pm-8pm'), ('1pm', '1pm-9pm'), ('1:30pm', '1:30pm-9:30pm'), ('2:30pm', '2:30pm-10:30pm'), ('3:30pm', '3:30pm-11:30pm')], default='', max_length=15),
        ),
    ]
