# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20181207_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('lastName', 'firstName')},
        ),
    ]
