# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20181210_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='buyer',
        ),
    ]
