# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_remove_employee_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='buyer',
            field=models.BooleanField(default=False),
        ),
    ]
