# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_employee_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='buyer',
            new_name='isBuyer',
        ),
    ]
